export type { CityData, CityBuilding, CityDistrict, Position3D, Bounds2D, Bounds3D, MapInteractionState, MapDisplayOptions, SelectiveRenderOptions, DirectoryRenderMode, ArchitectureMapProps, FileChange, Commit, PRVisualizationData, PRVisualizationProps, } from './types/cityData';
export type { ColorTheme, ColorFunction } from './types/themes';
export { THEMES, getBuildingColor } from './types/themes';
export type { ImportanceConfig, ImportanceResult, ImportanceLevel } from './types/importanceTypes';
export { DEFAULT_IMPORTANCE_LEVELS } from './types/importanceTypes';
export { type TreemapOptions, GridLayoutManager, SizingPresets, type SizingStrategy, } from './builder';
export { type UIMetadata, type FileCellUIMetadata, hasUIMetadata, getUIMetadata, setUIMetadata, getCellUIMetadata, setCellUIMetadata, DEFAULT_UI_METADATA, mergeWithDefaults, } from './types/ui-metadata';
export { type GitHubTreeResponse, getFilesFromGitHubTree } from './builder/FileTreeBuilder';
export { filterCityDataForSelectiveRender, filterCityDataForSubdirectory, filterCityDataForMultipleDirectories, } from './builder/cityDataUtils';
export { ArchitectureMapHighlightLayers, type ArchitectureMapHighlightLayersProps, } from './react/ArchitectureMapHighlightLayers';
export { useCodeCityData, type UseCodeCityDataOptions, type UseCodeCityDataReturn, } from './react/hooks/useCodeCityData';
export { MultiVersionCityBuilder, buildMultiVersionCity, type MultiVersionOptions, type MultiVersionResult, } from './builder';
export { drawLayeredBuildings, drawLayeredDistricts, drawGrid, drawLegend, type HighlightLayer, type LayerItem, type LayerRenderStrategy, } from './render/client/drawLayeredBuildings';
export { createFileColorHighlightLayers, getDefaultFileColorConfig, getFileColorMapping, type FileSuffixColorConfig, type FileSuffixConfig, type ColorLayerConfig, } from './utils/fileColorHighlightLayers';
export { createDrawContext, clearCanvas, type DrawContext } from './render/server/drawingUtils';
export { RenderMode, drawBuildings, drawDistricts } from './render/server/renderUtils';
export { calculateImportance, getStarCount, shouldShowImportance } from './utils/importanceUtils';
export { validateCodebaseViewConfig, autoFixGridConfig, type GridConfigValidationIssue, type GridConfigValidationReport, } from './builder/GridLayoutConfigValidator';
export { createPatternMatcher, matchesPattern, matchesAnyPattern, testPatterns, getMatchingPaths, PatternMatcherCache, type PatternMatchOptions, type PatternTestResult, } from './builder/PatternMatcher';
export { CityConfigBuilder, GroupSelector, GroupNaming, GridPositioner, GroupsList, type GridGroup, type GridSize, type WorkflowStep, type CurrentGroup, type RootItem, type CityConfigBuilderProps, type GroupSelectorProps, type GroupNamingProps, type GridPositionerProps, type GroupsListProps, type GridConfig, } from './react/config-builder';
//# sourceMappingURL=index.d.ts.map