"use strict";
// Auto-generated types from JSON schemas
// This file is generated by scripts/generate-schema-types.ts
// Do not edit manually
Object.defineProperty(exports, "__esModule", { value: true });
