/**
 * Represents a single MCP task submission received through the Principal MCP Bridge
 */
export interface MCPTaskSubmission {
  // Identity
  taskId: string; // Generated by bridge: "task-{timestamp}-{random}"
  submittedAt: number; // Timestamp when task was received

  // Task Content
  dependencyId: string; // Target dependency identifier
  taskSummary: string; // Brief task description
  taskDetails: string; // Full task details
  priority?: 'low' | 'normal' | 'high' | 'critical';
  tags?: string[];
  anchors?: string[];
  repositoryRoot?: string; // Optional repository hint from submitter

  // Resolution Status
  resolutionStatus: MCPTaskResolutionStatus;

  // Resolution Results
  dependencyResolved: boolean; // Whether dependency was found
  dependencyRepository?: string; // Full path to resolved dependency
  taskPath?: string; // Full path to written .task.md file
  taskWritten: boolean; // Whether task was written to Memory Palace

  // Error Tracking
  error?: string; // Error message if submission failed
}

/**
 * Task resolution status lifecycle
 */
export type MCPTaskResolutionStatus =
  | 'pending' // Just received, not yet processed
  | 'resolved' // Dependency found, task written to Memory Palace
  | 'unresolved' // Dependency not found, task not written
  | 'failed'; // Error during processing
